baseURL: http://example.org/
languageCode: en-us
title: My iGEM Team Site
theme: igem

params:
  # The team name at the iGEM Website
  team_name: 

  # Give the social media accounts here
  social_media:
    facebook: igemErlangen 
    twitter:  iGEM_Erlangen
    instagram: igem.erlangen
    youtube: UCxT11JmhRH62aBn-HZxGhQA
  
  # State the order of the team roles to appear
  team_members: ["Student Leader", "Student", "Instructor", "PI", "Advisor"]

staticDir:
  - content/team-members/images